### PR TITLE
fix json 5-3

### PR DESCRIPTION
**Pull request by weilixu**

### CODE REVIEW

**Comment by JacksonJ-KC** [comment]
This was giving undetermined because when adjacent_to is set to INTERIOR, the adjacent_zone must be defined. I tried fixing this by changing `adjacent_to` from `INTERIOR` to `IDENTICAL` which led to an unfortunate discovery in `get_surface_conditioning_category_dict` not being able to handle the `IDENTICAL` key. This seems like an issue. Do you agree @weilixu ?

**Comment by JacksonJ-KC** [comment]
Changed to EXTERIOR per your original suggestion to bypass the issue for now. https://github.com/pnnl/ruleset-checking-tool/pull/1478

**Comment by jugonzal07** [comment]
Hi all. I see this has already been merged and the spreadsheet was up-to-date as well.

**Comment by jugonzal07** [comment]
> Changed to EXTERIOR per your original suggestion to bypass the issue for now. #1478

Per Jackson's comment, this has been addressed

**Pull request closed without merging**
