### PR TITLE
Boiler_tcd_master

### PR DESCRIPTION
**Pull request by KarenWGard**

### CODE REVIEW

**Comment by weilixu** [comment]
Thanks Karen, I added Juan and Yun Joon as reviewer.
Also, could you remove your changes in the code base?
One in[disaggregate_master_test_json.py](https://github.com/pnnl/ruleset-checking-tool/pull/953/files#diff-be8cabdfb99ca01193bf70a6f89cb4226200c0ba0217a00444fbe436083fcd5d) and then other in [rct229/ruletest_engine/ruletest_jsons/scripts/excel_to_test_json.py](https://github.com/pnnl/ruleset-checking-tool/pull/953/files#diff-717006c24925dd31132dd7210c1809a701321fc660d5cc716d7049ffd13276f5)
Thank you!

**Comment by jugonzal07** [comment]
> Thanks Karen, I added Juan and Yun Joon as reviewer. Also, could you remove your changes in the code base? One in[disaggregate_master_test_json.py](https://github.com/pnnl/ruleset-checking-tool/pull/953/files#diff-be8cabdfb99ca01193bf70a6f89cb4226200c0ba0217a00444fbe436083fcd5d) and then other in [rct229/ruletest_engine/ruletest_jsons/scripts/excel_to_test_json.py](https://github.com/pnnl/ruleset-checking-tool/pull/953/files#diff-717006c24925dd31132dd7210c1809a701321fc660d5cc716d7049ffd13276f5) Thank you!

Yes, that would be a good idea. Frankly, I think it may be time for me to move the inputs away from the python file and ask folks to use a separate script to call the functions inside [excel_to_test_json.py](https://github.com/pnnl/ruleset-checking-tool/pull/953/files#diff-717006c24925dd31132dd7210c1809a701321fc660d5cc716d7049ffd13276f5) and [disaggregate_master_test_json.py](https://github.com/pnnl/ruleset-checking-tool/pull/953/files#diff-be8cabdfb99ca01193bf70a6f89cb4226200c0ba0217a00444fbe436083fcd5d). That would avoid these little conflicts that pop up in git that aren't really important with respect to version control.

**Comment by KarenWGard** [comment]
No problem.  I just copied and pasted from the develop branch for these two
files into the RT/KJW/Section_21 branch.

Thanks,

Karen

**Comment by weilixu** [comment]
This is merged from other branches. Close now

**Pull request closed without merging**
