### PR TITLE
Allow RMR templates in ruletest_engine

### PR DESCRIPTION
**Pull request by charliepnnl**
This modifies the generate_test_rmrs function in ruletest_engine.py to allow the use of RMR templates. See the function's documentation for an explanation of how templates can be used.

Added test code for the new version of generate_test_rmrs().

### CODE REVIEW

**Comment by mcneillj** [comment]
@charliepnnl @jugonzal07 do we still want this feature?  Wondering if the conflicts should be resolved, so we can merge this PR.

**Comment by charliepnnl** [comment]
@jugonzal07 what do you think?  Unless we are pretty sure we will not need templates at some point, we should probably merge this in.

**Comment by jugonzal07** [comment]
@charliepnnl let's find some time to talk about it. I would want to see an example go through before merging it in.

**Comment by jugonzal07** [comment]
Hi all, I made a great deal of updates to this branch and got an example working for envelope that really exercised the schema validation code. I see my changes to the branch above and hope you all can see the latest state of things too. Maybe I will demo this for you all on Wednesday.

**Comment by mcneillj** [comment]
@jugonzal07 wondering what the status of this is.

**Comment by charliepnnl** [comment]
I believe Juan has incorporated this into his code and this branch could now be removed.  Is that right @jugonzal07 ?

**Comment by jugonzal07** [comment]
Correct, I just did a last minute fix for formatting with black and things look good. I've made some minor updates to the pull request since finishing lighting and transformers that relate to bugs I found in the rmr_template logic but things feel pretty stable as of now.

**Review by mcneillj — APPROVED** [review]

**Pull request merged**
