### PR TITLE
Ruletest engine development

### PR DESCRIPTION
**Pull request by jugonzal07**
Hi James and Charlie,

I'm seeing I cannot automatically merge so would be interested in seeing where that happens. Let me know if that requires additional action on my part.

The vast majority of the updates here are on the ruletest side of the code. Exceptions relate to small changes to Charlie's code. These changes include:

- fixed a typo in "evalute_rules" in `engine.py`
- Used `os.path.dirname(__file__)` to define the path to the schema in `validate.py`
- Return `{'passed': True, 'error': None}` in validate if the RMR is blank (no reason to check an empty RMR) in `validate.py`

I'm not very attached to those changes so feel free to change them, especially if there's a better or more "Python" way of doing them.

### CODE REVIEW

**Comment by mcneillj** [comment]
@jugonzal07 it looks like you should merge the latest updates to the develop branch into this PR.  That may address the merge conflicts you have with validate.py file.

**Comment by jugonzal07** [comment]
Thanks @mcneillj and @charliepnnl 

I have made updates to the code. I have

- Merged in development
- Updated validate.py. Charlie and I discussed this and how we might require some python input from you James.
- Added a test script in test_ruletest_engine.py for transformer tests to run with `pipenv run pytest`
- Added run_ruletests.py to make things easier for folks to run tests. It's very basic for now.

**Comment by charliepnnl** [comment]
Thanks Juan.  Have a good break.

Charlie

From: Juan Gonzalez ***@***.***>
Reply-To: pnnl/ruleset-checking-tool ***@***.***>
Date: Wednesday, March 31, 2021 at 7:27 PM
To: pnnl/ruleset-checking-tool ***@***.***>
Cc: "Holly, Charlie A" ***@***.***>, Mention ***@***.***>
Subject: Re: [pnnl/ruleset-checking-tool] Ruletest engine development (#7)

Check twice before you click! This email originated from outside PNNL.


Thanks @mcneillj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcneillj&data=04%7C01%7Ccharlie.holly%40pnnl.gov%7C1816536f88484240b10d08d8f49c95ee%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637528300664814872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=INjmZHSNPJYV7VHHwxMMCA65VbCd%2BPEXqN72siDEYYg%3D&reserved=0> and @charliepnnl<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcharliepnnl&data=04%7C01%7Ccharlie.holly%40pnnl.gov%7C1816536f88484240b10d08d8f49c95ee%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637528300664824840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BSDz6XsgcAy2wndEfEwjk2tQa11w%2FlBtyFbRQ4QEaxc%3D&reserved=0>

I have made updates to the code. I have

  *   Merged in development
  *   Updated validate.py. Charlie and I discussed this and how we might require some python input from you James.
  *   Added a test script in test_ruletest_engine.py for transformer tests to run with pipenv run pytest
  *   Added run_ruletests.py to make things easier for folks to run tests. It's very basic for now.

**Review by mcneillj — APPROVED** [review]

**Review by charliepnnl — COMMENTED** [review]
I created a PR: https://github.com/pnnl/ruleset-checking-tool/pull/18 as one way of handling RMR templates.

I am starting to think that the complexity of the spreadsheets are going to get higher and higher as we try to handle deeply nested types of rules.  I'm thinking that writing the test cases is YAML might be more straight forward.

**Comment by jugonzal07** [comment]
Hi all,

I verified that the transformer rules are testing correctly despite the schema update. I manually broke the test JSON to verify that rules would catch schema errors and added logic to better communicate when this happens. I also merged in the latest development branch to ensure it would work well with that.

**Pull request merged**
