### PR TITLE
RT/JDJ/Rule5-38 (new numbering)

### PR DESCRIPTION
**Pull request by JacksonJ-KC**

### CODE REVIEW

**Comment by weilixu** [comment]
@JacksonJ-KC could you renumber this to 5-38 and base it to [RT/JG/section_5_numbering_update](https://github.com/pnnl/ruleset-checking-tool/tree/RT/JG/section_5_numbering_update)?

**Comment by JacksonJ-KC** [comment]
> @JacksonJ-KC could you renumber this to 5-38 and base it to [RT/JG/section_5_numbering_update](https://github.com/pnnl/ruleset-checking-tool/tree/RT/JG/section_5_numbering_update)?

@weilixu All set!

**Comment by Jiarongx-Xie** [comment]
@JacksonJ-KC Thank you Jackon! I have two comments regarding test case c. 
First, it should be floor surface, not roof (Line 232); second, the expected rule outcome should be undetermined, not fail (Line 180). Can you please double-check? Thanks!

**Comment by JacksonJ-KC** [comment]
@Jiarongx-Xie Thanks for the feedback. The intended outcome for test case c is fail, associated with case 3 of [the RDS](https://github.com/pnnl/ruleset-checking-tool/blob/RT/JG/section_5_numbering_update/docs/section5/Rule5-38.md). Now the surface is corrected to be a floor adjacent to ground.

**Comment by weilixu** [comment]
This is merged to the develop branch

**Pull request closed without merging**
