### PR TITLE
Rt/jg/lighting json

### PR DESCRIPTION
**Pull request by jugonzal07**
The lighting JSON work is mostly complete but I had a few comments for the team:

1) LightingSpaceType2019ASHRAE901TG37 from Enumerations2019ASHRAE90.1schema.json does not appear to have "Hotel". Here I substituted DORMITORY_LIVING_QUARTERS for now in rule-181-6ja-a , rule-181-6ja-b , rule-181-6ja-c , rule-181-6ja-d , rule-62-6j-a , rule-62-6j-b , rule-62-6j-c , rule-62-6j-d

2) I could not understand the TCD's values for rule-66-6o-d. I did my own interpretation.

3) I made a very basic schedule for the EFLH for lighting. I simply created a constant schedule equal to the EFLH value divided by 8760 (e.g., if EFLH = 4380, the schedule would be an 8760 length list equal to 0.5)

### CODE REVIEW

**Comment by jugonzal07** [comment]
Hi all,

Much like the transformer test JSON branch, this one is ready for review. The lighting schedules are still janky to meet the EFLH requirements of the TCD, but should be functional enough for Rule development.

**Review by mcneillj — CHANGES_REQUESTED** [review]
It looks like there are a number of changes that may have been updated in develop branch.  You should merge develop in to make sure this branch is starting from the most up to date version.

**Comment by jugonzal07** [comment]
Hi all,

I have merged in development and things look good. Let me know if you have any other thoughts.

Thanks!

**Review by charliepnnl — APPROVED** [review]
The sooner this is merged in the better for me.
Looks good.

**Pull request merged**
