### PR TITLE
Merge RMR to RMD rule test refactoring into JDJ refactor RMR branch

### PR DESCRIPTION
**Pull request by jugonzal07**
I updated all the ruletest JSONs from `rmr_*` keys to `rmd_*` keys. This included making a handful of changes to the tests to ensure they passed schema validation. NOTE-- many still fail to pass validation due to referenced `Schedules` not existing:

- Section 4, 5, 6, 19, 21, 22, 23 had issues with schedule references.

### CODE REVIEW

**Comment by JacksonJ-KC** [comment]
TCDs for 5-1 were done more manually because the rule uses RMDs of the different baseline rotations.

**Comment by JacksonJ-KC** [comment]
Test case 21-17-j was previously named 21-17-i, causing a duplicated test ID and an incomplete json.

**Comment by JacksonJ-KC** [comment]
FYI: Baseline system template for System 8 previously included a hot water loop and boiler in the Section 22 spreadsheet (it just didn't serve the HVAC system). This was confusing because rules for hot water systems are not applicable when the baseline system is 8, but the RMDs did include a hot water loop which made me confused why the rule was not applicable.

**Comment by JacksonJ-KC** [comment]
I fixed the failures for test cases:
6-8-e
22-5-c
22-5-d

Failures remaining to be addressed:
10-14-d
18-1-ap
18-1-ar
22-33-b

**Comment by claperle** [comment]
@jugonzal07 FYI, we updated the [Section 18 TCDs](https://onedrive.live.com/edit?id=796769604E905084!1922&resid=796769604E905084!1922&ithint=file%2cxlsx&authkey=!AFWyVVBHR7rhMmc&wdo=2&cid=796769604e905084) to deal with an issue we noticed.

**Comment by jugonzal07** [comment]
Thanks @JacksonJ-KC ! Lots of work between you and @claperle .

If you haven't already, I'd strongly encourage pulling in the [PR for undetermined and not_applicable tests not always being caught](https://github.com/pnnl/ruleset-checking-tool/pull/1422).

For most new sections, it wasn't too bad, but for old rule tests where we went back and added a bunch of `not_applicable` and `undetermined` rule cases, things were right for them to fail silently. I will share more during the stand up tomorrow.

**Pull request merged**
