### PR TITLE
Refactor all RMR and RMI to RMD

### PR DESCRIPTION
**Pull request by JacksonJ-KC**
I refactored all remaining occurrences of "RMR" throughout the implementation. This will also trigger the need to replace occurrences of "RMR" throughout each of the TCD spreadsheets. I have done this is in the Section 1 spreadsheet to confirm that the excel_to_test_json functionality remains intact after updating the spreadsheet keys 'rmr_template', 'rmr_transformation', etc.

I need to regenerate all test json's using the updated keys to pass the CI tests.

### CODE REVIEW

**Review by yunjoonjung-PNNL — APPROVED** [review]
Looks great to me. Thank you Jackson.

**Comment by weilixu** [comment]
Thanks for updating the RCT. I formatted the files for black check.
The CI failed due to test jsons - you can merge this PR once the CI passes

**Review by jugonzal07 — APPROVED** [review]
Looks great to me! I'll work on getting the rest of the spreadsheets converted to reflect this. It shouldn't be too bad to do. Thanks for doing this massive refactoring!

**Comment by JacksonJ-KC** [comment]
@weilixu @jugonzal07 CI tests are now passing 🎉

**Comment by jugonzal07** [comment]
> @weilixu @jugonzal07 CI tests are now passing 🎉

Well done! That's a nice chunk of work!🎉🎉🎉

**Pull request merged**
