### PR TITLE
Rule Test 16-1

### PR DESCRIPTION
**Pull request by jugonzal07**
First cut at rule test 16-1

### CODE REVIEW

**Comment by yunjoonjung-PNNL** [comment]
Juan,

We need ```proposed``` for all the cases because of the not applicable check. Can you add it to the RPD?

**Comment by yunjoonjung-PNNL** [comment]
Can you add the ```number_of_floors_served``` key in case (a)?

**Comment by weilixu** [comment]
Need revisit @jugonzal07 , this test json is not completed.

**Comment by yunjoonjung-PNNL** [comment]
Juan,

For case (c), could you check if the ```motor_power``` in baseline should be 46508.553 W (=62.369 hp)? Other than this case, all cases passed.

**Comment by yunjoonjung-PNNL** [comment]
> `rct229/rulesets/ashrae9012019/section16/__init__.py`

Hi Juan, Weili and I found that your testing json file is correct. So, please disregard my previous comment. My apologies!

**Pull request merged**
