### PR TITLE
Rule Test 16-7

### PR DESCRIPTION
**Pull request by jugonzal07**
First cut at Rule Test 16-7

### CODE REVIEW

**Comment by Jiarongx-Xie** [comment]
The json file works well so far, thanks!

**Comment by Jiarongx-Xie** [comment]
The latest versionlooks good to me. Thanks Juan!

**Review by Jiarongx-Xie — APPROVED** [review]
The latest version looks good to me. Thanks Juan!

**Comment by weilixu** [comment]
This PR is merged through 16-7 rule definition PR. close it now.

**Pull request closed without merging**
