### PR TITLE
Rule test 12-3

### PR DESCRIPTION
**Pull request by jugonzal07**
First cut at rule test 12-3 JSON. Also updates the ASHRAE229 schema to account for `automatic_controlled_percentage`

### CODE REVIEW

**Comment by yunjoonjung-PNNL** [comment]
Thank you, Juan. Could you address the following items?
Case (a) and (c)
- Falls under ```Undetermined``` instead of ```Pass``` b/c no_credit_comparison_data = hourly_multiplier_schedule_len_b = hourly_multiplier_schedule_len_p
- ```has_automatic_control``` key is missing
- ```lighting_space_type``` shouldn't be one of the following,
```[
    LIGHTING_SPACE.OFFICE_ENCLOSED,
    LIGHTING_SPACE.CONFERENCE_MEETING_MULTIPURPOSE_ROOM,
    LIGHTING_SPACE.COPY_PRINT_ROOM,
    LIGHTING_SPACE.LOUNGE_BREAKROOM_HEALTH_CARE_FACILITY,
    LIGHTING_SPACE.LOUNGE_BREAKROOM_ALL_OTHERS,
    LIGHTING_SPACE.CLASSROOM_LECTURE_HALL_TRAINING_ROOM_PENITENTIARY,
    LIGHTING_SPACE.CLASSROOM_LECTURE_HALL_TRAINING_ROOM_SCHOOL,
    LIGHTING_SPACE.CLASSROOM_LECTURE_HALL_TRAINING_ROOM_ALL_OTHER,
    LIGHTING_SPACE.OFFICE_OPEN_PLAN,
]```

**Comment by jugonzal07** [comment]
Updated.

**Comment by yunjoonjung-PNNL** [comment]
Case (a) and (c) fall into ```undetermined``` because ```no_credit_comparison_data == hourly_multiplier_schedule_len_b == hourly_multiplier_schedule_len_p```. To fix this, baseline and proposed schedules should NOT be identical. Could you fix this?

**Review by yunjoonjung-PNNL — APPROVED** [review]
Looks great to me. Thanks Juan.

**Pull request merged**
