### PR TITLE
RCT/JX/get_swh_components_associated_with_each_swh_bat function

### PR DESCRIPTION
**Pull request by Jiarongx-Xie**
This PR is not ready for review. It depends on the [get_building_segment_swh_bat function](https://github.com/pnnl/ruleset-checking-tool/pull/1517), which is not ready yet.

### CODE REVIEW

**Comment by weilixu** [comment]
Is this PR ready for review?

**Comment by Jiarongx-Xie** [comment]
> Is this PR ready for review?

No, it's not. It uses several other functions that have not yet been developed or finished.

**Comment by Jiarongx-Xie** [comment]
This function is not ready for review yet.

**Comment by yunjoonjung-PNNL** [comment]
Hi @Jiarongx-Xie, When you work on RCT, can you prioritize this PR? This is because I need this function to get 11-7 rule development wrapped up. Thank you!

**Comment by Jiarongx-Xie** [comment]
> Hi @Jiarongx-Xie, When you work on RCT, can you prioritize this PR? This is because I need this function to get 11-7 rule development wrapped up. Thank you!

Hi @yunjoonjung-PNNL , I have been working on testing this rule and have run into some problems. Its dev relies on the [get_building_segment_swh_bat](https://github.com/pnnl/ruleset-checking-tool/pull/1517/files) function you have been developing. I'll prioritize this PR and let's try to wrap up both functions. Thank you.

**Comment by yunjoonjung-PNNL** [comment]
> > Hi @Jiarongx-Xie, When you work on RCT, can you prioritize this PR? This is because I need this function to get 11-7 rule development wrapped up. Thank you!
> 
> Hi @yunjoonjung-PNNL , I have been working on testing this rule and have run into some problems. Its dev relies on the [get_building_segment_swh_bat](https://github.com/pnnl/ruleset-checking-tool/pull/1517/files) function you have been developing. I'll prioritize this PR and let's try to wrap up both functions. Thank you.

Thank you! I also have a few questions for the ```get_building_segment_swh_bat``` function. Let's see what the review comments look like.

**Comment by Jiarongx-Xie** [comment]
A new PR has been created to replace this one.

**Pull request closed without merging**
