### PR TITLE
Update to 0.0.18

### PR DESCRIPTION
**Pull request by jugonzal07**
Updated schema files to 0.0.18, JSON pointer enumerations to 0.0.18, and updated excel_to_test_json logic to account for temperatures required for boiler in 0.0.18.

### CODE REVIEW

**Review by yunjoonjung-PNNL — APPROVED** [review]
Thank you for doing this effort Juan! The changes look perfect to me. 
However, one note is if we merge this branch to ```develop```,  some of section 5, 6 rules will be broken because of the updated schema. I'd appreciate it if you could double-check this before you merge this branch. Thank you!

**Comment by jugonzal07** [comment]
Yes-- thank you Yun Joon. I noticed this as well. i should have noted that these PRs are all drafts for now as they fail pytests due to the schema update.

**Comment by weilixu** [comment]
I didnt know you can do draft PR on GITHUB. 
Most of the errors are key words changing - particularly enums in the 18 are slightly different from 12. Most of the enum has changed from `Type` to `Options`.
Another significant changes are the `CoolingSystem` and `HeatingSystem` where the `sensible_cool_capacity` is changed to `design_sensible_cool_capacity` and `heat_capacity` changed to `design_capacity`.
The HVAC key change affects many rules in section 5 because of the zone conditioning category function.

I will need to update all test jsons to gain full confidence on merging this PR.

**Comment by yunjoonjung-PNNL** [comment]
> 

Thank you for doing this Weili. 
I actually did the same thing in the ```RT/YJ/Schema_update_0012_0018``` branch. However, I haven't made the PR from this task (branch) because some section 6 rules haven't been done and are affected by the schema updates. However, as we are almost heading to the end of section 6 ( 6-1 and 6-2 are under review now), would it be the right timing to make ```RT/YJ/Schema_update_0012_0018``` branch PR (Rule 6-2 are affected by the schema update)?

**Comment by yunjoonjung-PNNL** [comment]
> I didnt know you can do draft PR on GITHUB. Good to learn new stuffs Most of the errors are key words changing - particularly enums in the 18 are slightly different from 12. Most of the enum has changed from `Type` to `Options`. Another significant changes are the `CoolingSystem` and `HeatingSystem` where the `sensible_cool_capacity` is changed to `design_sensible_cool_capacity` and `heat_capacity` changed to `design_capacity`. The HVAC key change affects many rules in section 5 because of the zone conditioning category function.
> 
> I will need to update all test jsons to gain full confidence on merging this PR.

**Review by weilixu — APPROVED** [review]

**Pull request merged**
