### PR TITLE
RT/JDJ/Rule5-41

### PR DESCRIPTION
**Pull request by JacksonJ-KC**

### CODE REVIEW

**Comment by Jiarongx-Xie** [comment]
Thank you Jackson for creating this test file. I saw that the field `heating_ventilating_air_conditioning_systems` is missing in the json file. This field will be needed by `get_zone_conditioning_category_dict(climate_zone, building)` ,which is further called by `get_zone_conditioning_category_dict(climate_zone, building)`. Can you please double-check? Thanks! @JacksonJ-KC

**Comment by JacksonJ-KC** [comment]
> Thank you Jackson for creating this test file. I saw that the field `heating_ventilating_air_conditioning_systems` is missing in the json file. This field will be needed by `get_zone_conditioning_category_dict(climate_zone, building)` ,which is further called by `get_surface_conditioning_category_dict(climate_zone, building)`. Can you please double-check? Thanks! @JacksonJ-KC

Hi @Jiarongx-Xie . The intent is to have the zone be determined as UNENCLOSED for these tests with no HVAC system, then the surface would be determined as UNREGULATED. I removed the terminal and reference to HVAC 1 that was there by mistake. 

Would it be easier if I test the rule with these tests to make sure we see the expected behavior? If the rule is ready to test, I will merge this branch into your branch with the rule implementation and run the tests to troubleshoot any issues on my side.

**Comment by Jiarongx-Xie** [comment]
> > Thank you Jackson for creating this test file. I saw that the field `heating_ventilating_air_conditioning_systems` is missing in the json file. This field will be needed by `get_zone_conditioning_category_dict(climate_zone, building)` ,which is further called by `get_surface_conditioning_category_dict(climate_zone, building)`. Can you please double-check? Thanks! @JacksonJ-KC
> 
> Hi @Jiarongx-Xie . The intent is to have the zone be determined as UNENCLOSED for these tests with no HVAC system, then the surface would be determined as UNREGULATED. I removed the terminal and reference to HVAC 1 that was there by mistake.
> 
> Would it be easier if I test the rule with these tests to make sure we see the expected behavior? If the rule is ready to test, I will merge this branch into your branch with the rule implementation and run the tests to troubleshoot any issues with the json.

Thanks @JacksonJ-KC for the clarification. That sounds a good idea. I just tested this rule 5-41 and it tested okay with the modified json file. 5-40 is more complex, we may do it the way you suggested.  I'm not very experienced in RCT development. Maybe I'll submit the PR for Weili to review and get back to you once it is ready to test. Thank you!

**Comment by Jiarongx-Xie** [comment]
> > > Thank you Jackson for creating this test file. I saw that the field `heating_ventilating_air_conditioning_systems` is missing in the json file. This field will be needed by `get_zone_conditioning_category_dict(climate_zone, building)` ,which is further called by `get_surface_conditioning_category_dict(climate_zone, building)`. Can you please double-check? Thanks! @JacksonJ-KC
> > 
> > 
> > Hi @Jiarongx-Xie . The intent is to have the zone be determined as UNENCLOSED for these tests with no HVAC system, then the surface would be determined as UNREGULATED. I removed the terminal and reference to HVAC 1 that was there by mistake.
> > Would it be easier if I test the rule with these tests to make sure we see the expected behavior? If the rule is ready to test, I will merge this branch into your branch with the rule implementation and run the tests to troubleshoot any issues with the json.
> 
> Thanks @JacksonJ-KC for the clarification. That sounds a good idea. I'm not very experienced in RCT development. Feel free to go ahead with this Rule 5-41. Rule 5-40 is more complex, maybe I need to submit an PR first for Weili to review. Then you can start. I'll get back to you. Thank you!

Update: I just tested this rule and found a bug in the rule file. I have fixed it and tested it. It looks all right now. So no worry about this rule. Thanks!

**Comment by weilixu** [comment]
the test json is merged, close this pull request now.

**Pull request closed without merging**
