### PR TITLE
Update schema to v0.0.4

### PR DESCRIPTION
**Pull request by mcneillj**
Latest RMR schema updates (as of today)

### CODE REVIEW

**Comment by charliepnnl** [comment]
Are you really intending to delete schema/Enumerations2019ASHRAE901.schema.json?  It is still referenced four places in ASHRAE229.schema.json.

**Comment by JasonGlazer** [comment]
I don't think it is being deleted, just some lines of it.

**Comment by mcneillj** [comment]
Changed this to v0.0.4 since that is the latest version of the schema.

**Comment by jugonzal07** [comment]
I'm ready to start making updates based on this JSON @charliepnnl . Let me know if there's any concerns you got.

**Review by jugonzal07 — APPROVED** [review]
Looks good to me! Ready to incorporate these changes.

**Comment by charliepnnl** [comment]
This branch seems to be missing two of the Enumeration schema.json files:
[Enumerations2019T24.schema.json](https://github.com/open229/ruleset-model-report-schema/blob/master/docs229/Enumerations2019T24.schema.json)
[EnumerationsRESNET.schema.json](https://github.com/open229/ruleset-model-report-schema/blob/master/docs229/EnumerationsRESNET.schema.json)

**Review by charliepnnl — CHANGES_REQUESTED** [review]
Need to copy over the Enumeration schema.json files

**Review by charliepnnl — APPROVED** [review]

**Comment by charliepnnl** [comment]
I copied over schema version 0.0.5 along with the latest `Enumerations2019ASHRAE901.schema.json` file.
The file `EnumerationsRESNET.schema.json` is referred to by `ASHRAE229.schema.json` and so I copied it over as well.

I also added  pytests for validate_rmr() to check that our example rmr files are schema valid. This also checks that the required enumeration files exist.

@mcneillj I think this is ready to merge.

**Pull request merged**
