### PR TITLE
Schema from early feb

### PR DESCRIPTION
**Pull request by JasonGlazer**
Replace older schema files with latest from early February. Untested.

### CODE REVIEW

**Review by charliepnnl — COMMENTED** [review]
Should this be merged into develop rather than master?
Otherwise, I think this is ready to merge.

**Comment by charliepnnl** [comment]
I have created a new branch `incorporating-new-schema` where I will fix the rest of our code to work with the new schema. It includes these changes.  It might be best to wait on merging this PR until I finish incorporating the new schema. At that point, this PR will no longer be needed.

**Comment by JasonGlazer** [comment]
@charliepnnl I agree, the new schema needs to be added to the develop branch along with your code fixes

**Comment by mcneillj** [comment]
@charliepnnl @JasonGlazer Can I close this PR?  I believe you already merged the schema updates in to develop, so this is not needed.

**Comment by JasonGlazer** [comment]
@mcneillj I believe you are correct.

**Comment by charliepnnl** [comment]
Yes.

**Comment by mcneillj** [comment]
Replaced by https://github.com/pnnl/ruleset-checking-tool/pull/2

**Pull request closed without merging**
