### PR TITLE
RS/YJ/Rule 5-9

### PR DESCRIPTION
**Pull request by yunjoonjung-PNNL**
When I tried to develop rule 5-9, I realized that this rule was already developed. This PR only added the undetermined message which wasn't included in the original code. Thanks!

### CODE REVIEW

**Review by weilixu — APPROVED** [review]

**Comment by weilixu** [comment]
5-9 is missing TCDs, we will need to revisit it once @JacksonJ-KC  develops the rule tests.

**Comment by weilixu** [comment]
> > 5-9 is missing TCDs, we will need to revisit it once @JacksonJ-KC develops the rule tests.
> 
> @weilixu This is on my to-do list. I am currently focusing section 1 RDS. Do you need me to reprioritize?

RDS has higher priority and then TCDs.

**Comment by yunjoonjung-PNNL** [comment]
@JacksonJ-KC 

When 5-9 TCD creation is done, could you push the file here?

**Comment by JacksonJ-KC** [comment]
Yes, will do!

*Jackson Jarboe* PE, LEED AP
Senior Energy Engineer
[image: image.png]
Work 860.430.9995

We are always looking for motivated professionals to join our team. See our
career options here <https://karpmanconsulting.net/available-careers>!

**Comment by yunjoonjung-PNNL** [comment]
Tested with #1204

**Comment by JacksonJ-KC** [comment]
> Tested with #1204

Woops, you beat me to it @yunjoonjung-PNNL

**Pull request merged**
