### PR TITLE
RS/YJ/Rule 11-12 (include only necessary codes) 

### PR DESCRIPTION
**Pull request by yunjoonjung-PNNL**
Based on PR https://github.com/pnnl/ruleset-checking-tool/pull/1543 comments, this PR only includes the codes related to rule 11-12. Thanks!

### CODE REVIEW

**Review by weilixu — APPROVED** [review]
i am a little concern on changing the `get_swh_uses_associated_with_each_building_segment` returning the `building_seg_id: sum_of_swh_use_value` key value pair as oppose to the RDS description: `building_seg_id: list of swh_use object`
However, if no other rule requires returning a list of swh_use objects, I am fine with this implementation.

**Comment by Jiarongx-Xie** [comment]
> i am a little concern on changing the `get_swh_uses_associated_with_each_building_segment` returning the `building_seg_id: sum_of_swh_use_value` key value pair as oppose to the RDS description: `building_seg_id: list of swh_use object` However, if no other rule requires returning a list of swh_use objects, I am fine with this implementation.

This function is required by multiple rules. 
Screenshot 2024-11-12 132549

**Comment by Jiarongx-Xie** [comment]
> > i am a little concern on changing the `get_swh_uses_associated_with_each_building_segment` returning the `building_seg_id: sum_of_swh_use_value` key value pair as oppose to the RDS description: `building_seg_id: list of swh_use object` However, if no other rule requires returning a list of swh_use objects, I am fine with this implementation.

This function is required by multiple rules. I think we may need to return the swh_use objects or their ids
Screenshot 2024-11-12 132549

**Review by Jiarongx-Xie — APPROVED** [review]
Great work, thank you Yun Joon!

**Pull request merged**
