### PR TITLE
TCD/JDJ/RULE19-12-1

### PR DESCRIPTION
**Pull request by JacksonJ-KC**
This json may have been merged into develop too soon. Starting a new pull request to track issues

### CODE REVIEW

**Comment by jugonzal07** [comment]
Hi @JacksonJ-KC,

Did you intend to remove the economizer in this commit?: 
https://github.com/pnnl/ruleset-checking-tool/pull/1126/commits/c6f6e58511e88549e0b29e9d1ba230c54dfec736

I'm guessing this is why 19-12 is returning tons of "not_applicable" for me after this.

**Comment by JacksonJ-KC** [comment]
> Hi @JacksonJ-KC,
> 
> Did you intend to remove the economizer in this commit?: [c6f6e58](https://github.com/pnnl/ruleset-checking-tool/commit/c6f6e58511e88549e0b29e9d1ba230c54dfec736)
> 
> I'm guessing this is why 19-12 is returning tons of "not_applicable" for me after this.


> Hi @JacksonJ-KC,
> 
> Did you intend to remove the economizer in this commit?: [c6f6e58](https://github.com/pnnl/ruleset-checking-tool/commit/c6f6e58511e88549e0b29e9d1ba230c54dfec736)
> 
> I'm guessing this is why 19-12 is returning tons of "not_applicable" for me after this.

Glad to hear the not_applicable test is working!! Haha, no - that was not intentional, I was doing manual data transfer between sheets and must have missed that chunk. Sorry about that.

**Comment by jugonzal07** [comment]
Looks good to me now! Thanks!

**Comment by jugonzal07** [comment]
@yunjoonjung-PNNL I will put out a PR for your **_Rule19-12_testing_** branch with the required fix for this.

**Comment by jugonzal07** [comment]
Hey Jackson, I have a PR to correct this issue with 12-1 here. Perhaps merging that into your test environment will address this issue.
https://github.com/pnnl/ruleset-checking-tool/pull/1135

**Comment by JacksonJ-KC** [comment]
> Hey Jackson, I have a PR to correct this issue with 12-1 here. Perhaps merging that into your test environment will address this issue. #1135

I see now, thanks!

**Review by yunjoonjung-PNNL — APPROVED** [review]
Looks great to me! Thank you Jackson.

**Comment by yunjoonjung-PNNL** [comment]
Closed b/c this TCD is the same as the one in develop.

**Pull request closed without merging**
